# Generated by Django 5.1.2 on 2024-10-12 16:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('date', models.DateField(default=datetime.date.today)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_starter', models.BooleanField(default=False)),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('offensive_rebounds', models.PositiveSmallIntegerField(default=0)),
                ('defensive_rebounds', models.PositiveSmallIntegerField(default=0)),
                ('steals', models.PositiveSmallIntegerField(default=0)),
                ('blocks', models.PositiveSmallIntegerField(default=0)),
                ('turnovers', models.PositiveSmallIntegerField(default=0)),
                ('defensive_fouls', models.PositiveSmallIntegerField(default=0)),
                ('offensive_fouls', models.PositiveSmallIntegerField(default=0)),
                ('free_throws_made', models.PositiveSmallIntegerField(default=0)),
                ('free_throws_attempted', models.PositiveSmallIntegerField(default=0)),
                ('two_pointers_made', models.PositiveSmallIntegerField(default=0)),
                ('two_pointers_attempted', models.PositiveSmallIntegerField(default=0)),
                ('three_pointers_made', models.PositiveSmallIntegerField(default=0)),
                ('three_pointers_attempted', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
            options={
                'db_table': 'player_stat',
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_make', models.BooleanField(default=False)),
                ('location_x', models.DecimalField(decimal_places=1, max_digits=3)),
                ('location_y', models.DecimalField(decimal_places=1, max_digits=3)),
                ('player_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='app.playerstat')),
            ],
            options={
                'db_table': 'shot',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_teams', to='app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_teams', to='app.team'),
        ),
    ]
